### ISSUE TITLE
Front page app description

### ISSUE THREAD

**Issue by edward-malouf** [codeforboston/jobhopper#103]
Write an introduction that describes the function of the JobHopper application.  The source of the data and its limitations will be included as well. If we have any governance information that might be included or it might be separate.

**Comment by edward-malouf** [comment]
Here are initial designs based on an 1152 x 700 laptop display. The site vocabulary needs to be established, for instance, when to use occupations versus jobs? I have tried to keep the language neutral in my mock-up.
[JobHopper Design. 2020 10.pdf](https://github.com/codeforboston/jobhopper/files/5371557/JobHopper.Design.2020.10.pdf)

**Comment by jedpittman** [comment]
Moving this to In Review. @alexjball , do you want to take a pass at this and add any issues in as needed to do this UI work?

**Comment by edward-malouf** [comment]
Annie created a first draft text document, it contains text for several pages, and points to new text for FAQ. https://cfb-public.slack.com/files/U3C6CMSVC/F01E5FH2N6L/jobhopper_site_text

**Comment by jedpittman** [comment]
Closing this issue since there's text added.
