### ISSUE TITLE
Add Redux reducer to manage frontend state

### ISSUE THREAD

**Issue by alexjball** [codeforboston/jobhopper#108]
This stores the options for the forms and the results of queries.

**Comment by alexjball** [comment]
We walked through creating a duck for states using redux-toolkit. I will be sending out a PR for it shortly.

@Dev1nxavier and @russ430 will take on the transitions duck, and @sashamaryl and I will take on the socs duck.

**Comment by jedpittman** [comment]
Moving to next column; work in progress for testing/integration.

**Comment by jedpittman** [comment]
@alexjball I'm closing this since we have two items that are merged for it. I can reopen if needed or we can create any new issues as needed just let me know.
