### ISSUE TITLE
Data Team: SOC Codes

### ISSUE THREAD

**Issue by rscottlundgren** [codeforboston/jobhopper#11]
There's a question of whether the SOC codes have been updated between 2010 & 2018. We are presently using 2010 SOC Codes - would need to confirm what, if any, differences there may be between the years.

**Comment by bhushan-choudhari** [comment]
1) In comparison with the 2010 SOC, the 2018 SOC had a net gain of 27 detailed occupations and 1
minor group. 
2) Of the 867 occupations in the 2018 structure, 
    i) 382 remained completely unchanged from the 2010 SOC, 
    ii) 356 had at least a definition change, 
    iii) 131 had at least a title change, and 
    iv) 115 had at least a code change. 
3) Most of the definition changes (254) were editorial revisions or clarifications that did not change occupational content. 
4) Therefore, no substantive change occurred for **about 88 percent** of the detailed occupations in the 2010 SOC.

**Comment by bhushan-choudhari** [comment]
https://www.bls.gov/soc/2018/home.htm

**Comment by jedpittman** [comment]
@rscottlundgren can we please assign this to @aniyip. Again the goal is to get the data checked into the /data folder in some reasonable place in a usable format along with any scripts needed to retrace the work. If possible, follow #22 and update the process to incorporate that data (if the data is large). If it is quite small (< 10mb) it could also be directly incorporated into the sqlite db under /data. The main point is that we target the .sqlite db must be kept under 50mb to avoid issues.

**Comment by jedpittman** [comment]
Closing issue. This is covered by other issues in the sprint already including the data that has been loaded by Lillian into the postgres db.
