### ISSUE TITLE
Create link to O*net 

### ISSUE THREAD

**Issue by edward-malouf** [codeforboston/jobhopper#110]
In the results table, the job name will provide a link to O*net. This will provide further information about the occupation.

**Comment by jedpittman** [comment]
--There are no cases where the decimal code is not 00
select substring(soc_decimal_code, 9, 2), * from jobs_blsoes
where substring(soc_decimal_code, 9, 2) <> '00'

--Code always matches decimal -> non-decimal
select substring(soc_decimal_code, 1, 7), * from jobs_blsoes
where substring(soc_decimal_code, 1, 7) <> soc_code

--Affirming evidence that codes don't mismatch from title. unique relationships.
select count(distinct soc_code) from jobs_blsoes where file_year = '2019' -- 1316
select count(1) from (select distinct soc_code, soc_title from jobs_blsoes where file_year = '2019') as x --1316
