### ISSUE TITLE
Set up Chromatic to host stories and run UI tests

### ISSUE THREAD

**Issue by alexjball** [codeforboston/jobhopper#112]
Storybook provides a free service for screenshot diffing called [Chromatic](https://www.chromatic.com/pricing). We should integrate Chromatic into our CI process using Github Actions following [the Getting Started guide](https://www.chromatic.com/docs/) and [Github Actions configuration](https://www.chromatic.com/docs/github-actions). Publish to Chromatic and run UI tests when code is merged into develop.

Chromatic can run on PR's between branches of the same repo but not securely across forks. Solutions are devs can set up their own chromatic projects, or we could allow people to push to feature branches on the cfb repo.

**Comment by jedpittman** [comment]
Are you talking about this: https://storybook.js.org/docs/react/workflows/visual-testing and thereby adding Chromatic? Or are you talking about something else?

**Comment by alexjball** [comment]
Yeah that's what I'm talking about. Our redux logic is covered by unit tests, our components are covered by these UI tests, and our containers/controllers are covered by Jest functional tests.

**Comment by alexjball** [comment]
Admin steps needed to set up Chromatic on Cfb repo:
- Leads or someone with access to codeforboston org needs to sign up for Chromatic and authorize the chromatic app on github https://www.chromatic.com/docs/access#linked-projects
- Add project token to github action secret
- Make sure UI review and tests are enabled in Chromatic settings

**Comment by jedpittman** [comment]
closing issue. this is handled by #199
