### ISSUE TITLE
Input page text confirmation

### ISSUE THREAD

**Issue by edward-malouf** [codeforboston/jobhopper#115]
Finalize all static text on input page, for instance, "Enter Occupation" and make clear that the default wage data is national wage data. There are other elements that will need to be considered.

**Comment by edward-malouf** [comment]
Draft text on laptop designs
[Uploading JobHopper Design 2020 10-13.pdf…]()

**Comment by jedpittman** [comment]
Moving this to In Review. @alexjball , do you want to review this and add any issues needed to implement?

**Comment by jedpittman** [comment]
I think we're at a final (more or less) version of the wording. Closing this for now.
