### ISSUE TITLE
Automatically Deploy storybook on version branches on CI

### ISSUE THREAD

**Issue by alexjball** [codeforboston/jobhopper#133]
When a PR is merged into a working branch (e.g. V1.1.0) We should build and deploy storybook so that we can easily review up-to-date UI with designers. Unfortunately we cannot deploy storybook for pull requests because Github Actions does not allow exposing secrets (deploy keys) to PR's from forks, as that is a security issue.

https://www.learnstorybook.com/design-systems-for-developers/react/en/review/

**Comment by jedpittman** [comment]
Storybook is integrated into CI. Closing this issue.
