### ISSUE TITLE
Deploy React Application Code Automatically (Not Storybook)

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#136]
This will continue to depend on our circumstance for later deployment -- this issue is a stopgap to allow us to continue to modify/update our UI and deploy it before we make our absolute final decision on hosting/etc.

Goal: Deploy the built storybook/ui code automatically to a test location so it can be reviewed.

**Comment by alexjball** [comment]
I'm going to set up deployment to firebase hosting since I've used it before. Easy enough to switch to something later if we want.
