### ISSUE TITLE
Update TransitionPage to match Ed's Prototype

### ISSUE THREAD

**Issue by alexjball** [codeforboston/jobhopper#146]
Per discussion with team on 10/27/2020 we're updating the components per this figma link. Details follow.
https://www.figma.com/file/fXQirNUcSUBC5KTJ7hYBO6/JobHopper-interface-2?node-id=22%3A16
* Logo
-- Too small
* Transitions table
--  Reduce line spacing
--  Add links to O*net to job names’
--  Add search bar
--  Reduce width
* Typography
--  Header 24 pt bold
--  Text 18 pt

**Comment by alexjball** [comment]
https://www.figma.com/file/fXQirNUcSUBC5KTJ7hYBO6/JobHopper-interface-2?node-id=22%3A16

**Comment by jedpittman** [comment]
This is done. Closing per Alex. B.
