### ISSUE TITLE
Transitions User Filter

### ISSUE THREAD

**Issue by edward-malouf** [codeforboston/jobhopper#148]
Context
Determine approach for filtering data that displays in the tree map/matching table

1. Default set at >1% (bias here is toward quicker rendering?) How could the user change this in a design mockup?
2. Default at 50 results, but user can call for more (How could the user change this in a design mockup?)

Deliverables:
1. Create updates to figma and/or other mockup to ensure that the look and feel is setup
2. Create a follow up issue for implementation.

**Comment by edward-malouf** [comment]
A note stating that results are all greater than 1%. To see less requires a selection by the user.

**Comment by jedpittman** [comment]
Subsumed by other work and requests from our stakeholders
