### ISSUE TITLE
Create top-level page layout

### ISSUE THREAD

**Issue by alexjball** [codeforboston/jobhopper#154]
This renders the top-bar and the router component. It is rendered directly by the App component.

**Comment by jedpittman** [comment]
potentially closing as completed with #164 ?

**Comment by edward-malouf** [comment]
Yes


Content • Design Collaborative LLC
433 Country Way
Scituate, MA 02066
781-378-1484 

Accessibility is an excuse for good design
http://contentdesign.me/accessibility-visitor-experience/
