### ISSUE TITLE
Migrations for Jobs 0004 and 0003 do not work backwards

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#157]
While this is generally a minor item, the migrations for 0003 and 0004 do not work when running backwards on a migrated database e.g. 

Resolution will ensure that the migrations work forward and backwards. 

Suggested fix is to create two python functions, one to wrap the forward work already present and then a second to wrap some sql to truncate the data for the fields:
pi = max length = 1
occleaveshare = max length = 8

sample code
`migrations.RunPython(add_states, remove_states)`

**Comment by l-cheung** [comment]
Side effect of https://github.com/codeforboston/jobhopper/pull/178
