### ISSUE TITLE
Requirements: Understanding O*Net API

### ISSUE THREAD

**Issue by rscottlundgren** [codeforboston/jobhopper#16]
O*Net API: [https://services.onetcenter.org/reference/](https://services.onetcenter.org/reference/)

1. Match up SOC codes with plain language and figure out user friendly filtering
2. Research tool to translate job titles to SOC codes - Onet API
3. How do we get education/skills and wages/wage ranges for jobs?
4. Find data for local share of the market
6. Where are we getting wage data and local employment share

**Comment by gschubert** [comment]
Wage series can be pulled through the BLS API or as a static data set from the BLS website by manual pull. Relevant tables are from the OES and can be pulled via a series identifier that looks like this:
![image](https://user-images.githubusercontent.com/35321293/88113473-d864ef00-cb7f-11ea-8d8e-0924f664f528.png)
Manual wage table source would be this - has **wage and employment data** by SOC at an MSA level
https://www.bls.gov/oes/tables.htm
**Local share of the market** can be constructed from the employment data from the same source.

**Comment by rscottlundgren** [comment]
O*Net - Education - [https://services.onetcenter.org/reference/mnm/career/education](https://services.onetcenter.org/reference/mnm/career/education)
O*Net - Salary - [https://services.onetcenter.org/reference/mnm/career/outlook](https://services.onetcenter.org/reference/mnm/career/outlook)

BLS - Developer Info -  [https://www.bls.gov/developers/api_faqs.htm#basics2](https://www.bls.gov/developers/api_faqs.htm#basics2)

**Comment by EndyPremier** [comment]
3. Education/Skill + Wages

> Education
> `https://services.onetcenter.org/ws/mnm/careers/[O*NET-SOC Code]/education`
> https://services.onetcenter.org/reference/mnm/career/education

> Skills
> `https://services.onetcenter.org/ws/mnm/careers/[O*NET-SOC Code]/skills`
> https://services.onetcenter.org/reference/mnm/career/skills

> Wages Range
> `https://services.onetcenter.org/ws/mnm/careers/[O*NET-SOC Code]/job_outlook`
> https://services.onetcenter.org/reference/mnm/career/outlook

> Job Share (State Level)
> `https://services.onetcenter.org/ws/mnm/careers/[O*NET-SOC Code]/check_out_my_state`
> https://services.onetcenter.org/reference/mnm/career/state

> Full Report (all before and more) for specific job
> `https://services.onetcenter.org/ws/mnm/careers/[O*NET-SOC Code]/report`
> https://services.onetcenter.org/reference/mnm/career/report

**Comment by benjaminkniaz** [comment]
1. and 2. could possibly be solved using keyword search: 

https://services.onetcenter.org/ws/mnm/search?keyword=architect

```
{
   "keyword" : "architect",
   "start" : 1,
   "end" : 20,
   "total" : 66,
   "link" : [
      {
         "href" : "https://services.onetcenter.org/ws/mnm/search?keyword=architect&start=21&end=40",
         "rel" : "next"
      }
   ],
   "career" : [
      {
         "href" : "https://services.onetcenter.org/ws/mnm/careers/17-1011.00/",
         "code" : "17-1011.00",
         "title" : "Architects",
         "tags" : {
            "bright_outlook" : true,
            "green" : true,
            "apprenticeship" : false
         }
      },
      {
         "href" : "https://services.onetcenter.org/ws/mnm/careers/17-3011.01/",
         "code" : "17-3011.01",
         "title" : "Architectural Drafters",
         "tags" : {
            "bright_outlook" : false,
            "green" : true,
            "apprenticeship" : true
         }
      },
      {
         "href" : "https://services.onetcenter.org/ws/mnm/careers/25-1031.00/",
         "code" : "25-1031.00",
         "title" : "Architecture Teachers, Postsecondary",
         "tags" : {
            "bright_outlook" : true,
            "green" : false,
            "apprenticeship" : false
         }
      }
...
   ]
}
```

**Comment by jedpittman** [comment]
At this point we have the information from Onet more-or-less wrapped up.
The next step is to start getting the wage information from BLS. 
Onet is only a pass-through for this information, see this information from their site:

The bright_outlook element is present if the career meets Bright Outlook criteria. One or more category elements are returned to indicate the criteria matched:

Grow Rapidly - the career will grow rapidly in the next few years
Openings - the career will have large numbers of openings
New & Emerging - this is a new and emerging career
The salary element provides annual and/or hourly wages, from the BLS Occupational Employment Statistics external site wage estimates. The soc_code attribute indicates the SOC code for which the estimate was published. The median, 10th percentile, and 90th percentile estimates are provided when available. If the estimated salary is greater than the maximum reported by BLS, the maximum number will be returned in an element suffixed by "_over": for example, an annual_median_over element would be present and the annual_median element would be missing.

The green element is present when the career has been identified as part of the green economy. One of three category values is returned:

Increased Demand - the green economy will increase the demand for this type of work
Changed Work - the green economy will change the work and skills needed on the job
New & Emerging - the career represents a new type of work created by the green economy
My Next Move illustrates each Green occupation with a graphic, as shown below. Developers can download multiple sizes and formats from the O*NET Graphics page.
