### ISSUE TITLE
[Volunteer Sprint] Security - Add rate limiting/throttling

### ISSUE THREAD

**Issue by l-cheung** [codeforboston/jobhopper#163]
Goal: Investigate/add rate limiting/throttling to prevent users from hitting the API endpoints too hard

Possible places to start:
* Cloudflare could provide support for rate limiting at the domain level
* https://medium.com/analytics-vidhya/throttling-requests-with-django-rest-framework-for-different-http-methods-3ab0461044c
* https://www.django-rest-framework.org/api-guide/throttling/
* https://django-ratelimit.readthedocs.io/en/stable/

**Comment by jedpittman** [comment]
This kind of thing where a particular user is only allowed so many requests per day is good. (300 seems like a generous number):
https://www.django-rest-framework.org/api-guide/throttling/

Cloudflare would be something I'd avoid since we don't know what the hosting mechanism will be.

**Comment by l-cheung** [comment]
Complete (see #175)
