### ISSUE TITLE
Set up SSL certificate using Cloudflare and/or web host options

### ISSUE THREAD

**Issue by rfgarth** [codeforboston/jobhopper#169]
It is only possible to do this after there is a purchased domain name for Jobhopper (ticket https://github.com/codeforboston/jobhopper/issues/170 ).

The first step to setting up SSL for Jobhopper is to obtain an SSL certificate. Here are the two simplest options for accomplishing that.

**Option 1 (Cloudflare) -- recommended, especially if already planning to use Cloudflare for DDoS protection**
If Jobhopper chooses to use Cloudflare, Cloudflare also provides certificates. Documentation from Cloudflare: https://www.cloudflare.com/ssl/ . The steps to complete are:
1. Cloudflare offers an option to use SSL between the wider internet and Cloudflare, which should be selected. No work is required in this step beyond choosing this option in Cloudflare.
2. Cloudflare offers a way to use a certificate signed by Cloudflare to encrypt between Cloudflare and the Jobhopper servers, which they call a Cloudflare "origin CA" certificate. Using the Cloudflare account, we obtain a certificate from them. This certificate must be installed with the web host.

The specific actions to install the Cloudflare certificate with the web host for step 2 will depend on the web host chosen. Ideally, it should be something along the lines of obtaining a file from Cloudflare and providing it to some sort of wizard or tool in the web host admin page. If the web host does not provide this functionality, you must refer to the alternative options (options 3 and 4) in the ticket linked at the bottom of this post.

**Option 2 (Integration):**
Many hosting providers offer SSL certificate setup, installation, and maintenance as part of their hosting package, often with no additional charge. In this scenario, a web admin for Jobhopper would log in to the web admin portal, find a button or something for generating SSL certificates, and follow the prompts. If this option is available, it is recommended as an easy and reliable way to set up a certificate. Example reputable providers that appear to offer this as of the time of this ticket: Dreamhost (https://dreamhost.com), Bluehost (https://bluehost.com), Hostgator (https://hostgator.com) .

Note that this is also compatible with using Cloudflare. In this case, we complete the prompts with the webhost, then do Cloudflare step 1 above in the same way, and then in the end step 2 in Cloudflare becomes the Full SSL option from Cloudflare using the certificate generated by the hosting provider. In this case, rather than installing the Cloudflare certificate on the hosting provider, we instead supply the hosting provider's certificate to Cloudflare.

More discussion of tradeoffs and additional alternative options of greater complexity can be found in this comment https://github.com/codeforboston/jobhopper/issues/62#issuecomment-718916695 .

**Comment by rfgarth** [comment]
Note: this tracker created in response to https://github.com/codeforboston/jobhopper/issues/62 .

**Comment by rfgarth** [comment]
Blocked by https://github.com/codeforboston/jobhopper/issues/170 .

**Comment by jedpittman** [comment]
Closing as obsolete.
