### ISSUE TITLE
Requirements: Location Data

### ISSUE THREAD

**Issue by rscottlundgren** [codeforboston/jobhopper#17]
O*Net API: [https://services.onetcenter.org/reference/](https://services.onetcenter.org/reference/)
BLS API: [https://www.bls.gov/developers/](https://www.bls.gov/developers/)

How can we gather location data based off size (local -> MSA -> state -> national)

4. Find data for local share of the market
7. What admin or account data are collecting? - locations table at least - zipcodes and county's
8. Explore commuting zones

**Comment by jedpittman** [comment]
Sample Code: 
https://www.bls.gov/developers/api_python.htm

Example Data Sets and specific Series Codes can be found and plugged into the sample code. 
https://www.bls.gov/data/#projections

https://data.bls.gov/oes/#/occGeo/One%20occupation%20for%20multiple%20geographical%20areas

Also an MSA lookup is available here, but perhaps we might want to get it once and then store the information:
https://www.huduser.gov/portal/datasets/geotool/select_Geography.odn

---
Sample Output from the code is below
+-------------+------+--------+---------+-----------+
|  series id  | year | period |  value  | footnotes |
+-------------+------+--------+---------+-----------+
| CUUR0000SA0 | 2014 |  M12   | 234.812 |           |
| CUUR0000SA0 | 2014 |  M11   | 236.151 |           |
| CUUR0000SA0 | 2014 |  M10   | 237.433 |           |
| CUUR0000SA0 | 2014 |  M09   | 238.031 |           |
| CUUR0000SA0 | 2014 |  M08   | 237.852 |           |
| CUUR0000SA0 | 2014 |  M07   | 238.250 |           |
| CUUR0000SA0 | 2014 |  M06   | 238.343 |           |
| CUUR0000SA0 | 2014 |  M05   | 237.900 |           |
| CUUR0000SA0 | 2014 |  M04   | 237.072 |           |
| CUUR0000SA0 | 2014 |  M03   | 236.293 |           |
| CUUR0000SA0 | 2014 |  M02   | 234.781 |           |
| CUUR0000SA0 | 2014 |  M01   | 233.916 |           |
| CUUR0000SA0 | 2013 |  M12   | 233.049 |           |
| CUUR0000SA0 | 2013 |  M11   | 233.069 |           |
| CUUR0000SA0 | 2013 |  M10   | 233.546 |           |
| CUUR0000SA0 | 2013 |  M09   | 234.149 |           |
| CUUR0000SA0 | 2013 |  M08   | 233.877 |           |
| CUUR0000SA0 | 2013 |  M07   | 233.596 |           |
| CUUR0000SA0 | 2013 |  M06   | 233.504 |           |
| CUUR0000SA0 | 2013 |  M05   | 232.945 |           |
| CUUR0000SA0 | 2013 |  M04   | 232.531 |           |
| CUUR0000SA0 | 2013 |  M03   | 232.773 |           |
| CUUR0000SA0 | 2013 |  M02   | 232.166 |           |
| CUUR0000SA0 | 2013 |  M01   | 230.280 |           |
| CUUR0000SA0 | 2012 |  M12   | 229.601 |           |
| CUUR0000SA0 | 2012 |  M11   | 230.221 |           |
| CUUR0000SA0 | 2012 |  M10   | 231.317 |           |
| CUUR0000SA0 | 2012 |  M09   | 231.407 |           |
| CUUR0000SA0 | 2012 |  M08   | 230.379 |           |
| CUUR0000SA0 | 2012 |  M07   | 229.104 |           |
| CUUR0000SA0 | 2012 |  M06   | 229.478 |           |
| CUUR0000SA0 | 2012 |  M05   | 229.815 |           |
| CUUR0000SA0 | 2012 |  M04   | 230.085 |           |
| CUUR0000SA0 | 2012 |  M03   | 229.392 |           |
| CUUR0000SA0 | 2012 |  M02   | 227.663 |           |
| CUUR0000SA0 | 2012 |  M01   | 226.665 |           |
| CUUR0000SA0 | 2011 |  M12   | 225.672 |           |
| CUUR0000SA0 | 2011 |  M11   | 226.230 |           |
| CUUR0000SA0 | 2011 |  M10   | 226.421 |           |
| CUUR0000SA0 | 2011 |  M09   | 226.889 |           |
| CUUR0000SA0 | 2011 |  M08   | 226.545 |           |
| CUUR0000SA0 | 2011 |  M07   | 225.922 |           |
| CUUR0000SA0 | 2011 |  M06   | 225.722 |           |
| CUUR0000SA0 | 2011 |  M05   | 225.964 |           |
| CUUR0000SA0 | 2011 |  M04   | 224.906 |           |
| CUUR0000SA0 | 2011 |  M03   | 223.467 |           |
| CUUR0000SA0 | 2011 |  M02   | 221.309 |           |
| CUUR0000SA0 | 2011 |  M01   | 220.223 |           |
+-------------+------+--------+---------+-----------+

**Comment by jedpittman** [comment]
closing issue as requirements phase is completed.
