### ISSUE TITLE
Acquire a domain name

### ISSUE THREAD

**Issue by dlaikhter** [codeforboston/jobhopper#170]
This is a requirement for setting up HTTPS/SSL: https://github.com/codeforboston/jobhopper/issues/62

Summary of our research here: https://github.com/codeforboston/jobhopper/issues/62#issuecomment-718916695

Find a domain name registrar, for example: NameCheap, HostGator, BlueHost, Cloudflare.

Just fyi, jobhopper.com is taken.  However, jobhopper.dev is available for $14.98/yr and hopper.jobs is available on name.com for $159.00/yr.

**Comment by jedpittman** [comment]
purchased jobhopper.live ; closing this issue.
