### ISSUE TITLE
Security – Generate CSR Code 

### ISSUE THREAD

**Issue by jasongreenfield-rf** [codeforboston/jobhopper#171]
Generating a CSR code is necessary to close https://github.com/codeforboston/jobhopper/issues/62 

You will generate a CSR code if you are doing either option 3 (certbot) or option 4 (paid certificate and paid provider) as explained in this comment https://github.com/codeforboston/jobhopper/issues/62#issuecomment-718916695

--------------------

Option 3 (Certbot)

Certbot will also install the certificates and automatically change your nginx configuration and turn on https in a single step. There is also an option to have Cerbot just install the certificates and not have it change your nginx configuration. Certbot also handles multiple webservers on multiple operating systems (so it does not necessitate nginx). 

First, install snapd: https://snapcraft.io/docs/installing-snapd/

Install certbot: `sudo snap install --classic certbot`

Prepare the certbot command: `sudo ln -s /snap/bin/certbot /usr/bin/certbot`

Run certbot (this command gets a certificate and has Certbot edit your Nginx configuration automatically to serve it. This turns on HTTPS access in a single step.): `sudo certbot --nginx`

For reference: https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx

--------------------

Option 4 (paid certificate and paid provider)

To generate a CSR code, run the following command in your server's terminal:
`openssl req -new -newkey rsa:2048 -nodes -keyout yourdomainname.key -out yourdomainname.csr`

Then continue to https://github.com/codeforboston/jobhopper/issues/172

For reference: https://simpleisbetterthancomplex.com/tutorial/2016/05/11/how-to-setup-ssl-certificate-on-nginx-for-django-application.html

**Comment by jedpittman** [comment]
Closing this as done separately.
