### ISSUE TITLE
Activating SSL certificate

### ISSUE THREAD

**Issue by dlaikhter** [codeforboston/jobhopper#172]
Link to research findings: https://github.com/codeforboston/jobhopper/issues/62#issuecomment-718916695

This step will require a hostname, see: https://github.com/codeforboston/jobhopper/issues/170

Option 3, Using ACME client (Certbot):
https://letsencrypt.org/getting-started/
https://certbot.eff.org/
Some providers may not have an integration with Let's Encrypt, but you can use Certbot to help with generating, activating, and renewing certificates.
List of providers and their compatibility with Certbot:
https://certbot.eff.org/hosting_providers/
Depending on the provider, you may have to email/upload your custom certificates to them.  Many also have APIs that you can use to help automate this process.

-------

Option 4, using a paid certificate (namecheap):
You will need to generate a CSR, see: https://github.com/codeforboston/jobhopper/issues/171
The provider will then activate your ssl cert, and email you your certificates.
https://www.namecheap.com/support/knowledgebase/article.aspx/794/67/how-do-i-activate-an-ssl-certificate

Next steps here to install SSL cert: https://github.com/codeforboston/jobhopper/issues/173

**Comment by jedpittman** [comment]
certbot information has been done by alex ball. closing this.
