### ISSUE TITLE
Security - Install SSL Certificate 

### ISSUE THREAD

**Issue by jasongreenfield-rf** [codeforboston/jobhopper#173]
Installing an SSL Certificate is necessary to close #62

You will install your SSL certificate if you are doing either option 3 (certbot) or option 4 (paid certificate and paid provider) as explained in this comment #62 (comment)

---

Option 3 (certbot) 

If you are using certbot, this step is automatically included in the code you executed as part of ticket https://github.com/codeforboston/jobhopper/issues/171

Certbot (https://certbot.eff.org/) will automatically generate certificates, put them in the right directory, and update your nginx configuration. (Note: certbot is agnostic to what your web server software is and what system your server is running on). 

Certbot can also automatically renew your certificates. 

---

Option 4(manually upload your certificates and change your nginx configuration):

Your certificate should have come with the following two files:
- your_domain_name.crt
- your_domain_name.ca-bundle

You will concatenate the two files:
```
cat your_domain_name.crt your_domain_name.ca-bundle >> your_domain_name_cert_chain.crt
```
and then upload those files to your server using scp:
```
scp your_domain_name_cert_chain.crt ubuntu@52.26.32.151:/home/ubuntu
```
Next move the following two files to /etc/ssl/:
- your_domain_name_cert_chain.crt
- your_domain_name.key (this was generated when you made your CSR, see ticket 169)

Lastly, add the following lines to your nginx configuration: 
```
server {
    listen 443;  

    ssl on;  
    ssl_certificate /etc/ssl/simpleacademy_cert_chain.crt;  
    ssl_certificate_key /etc/ssl/simpleacademy.key;  

    location / {
        proxy_set_header X-Forwarded-Proto https;  
    }
}
```

At this point, you have completed the set up of HTTPS and your SSL certificate and you can close ticket https://github.com/codeforboston/jobhopper/issues/62

For reference: https://simpleisbetterthancomplex.com/tutorial/2016/05/11/how-to-setup-ssl-certificate-on-nginx-for-django-application.html

**Comment by jedpittman** [comment]
Closing as obsolete.
