### ISSUE TITLE
soc-list does not filter down results

### ISSUE THREAD

**Issue by alexjball** [codeforboston/jobhopper#183]
Starting from a fresh docker container, if I visit http://127.0.0.1:8000/api/v1/jobs/soc-list/, I see 100k+ results, but there are only 1.5k distinct soc-codes. I would expect the [queryset](https://github.com/codeforboston/jobhopper/blob/49711b0b0130c707317552455274c4a7a2ef1ac0/jobs/api.py#L44) to do the appropriate filtering but for some reason it does not.

```
jobhopper_dev=# select count(distinct(soc_code, soc_title)) from jobs_blsoes;
 count 
-------
  1513
(1 row)
```

**Comment by edward-malouf** [comment]
Site cannot be reached message when I tried to open link.

**Comment by l-cheung** [comment]
Can fix this weekend. @edward-malouf the link only works if you have the server running locally (from the setup instructions here: https://github.com/codeforboston/jobhopper/blob/develop/References/Overview.md)

**Comment by l-cheung** [comment]
PR:  #187
