### ISSUE TITLE
Site color specs

### ISSUE THREAD

**Issue by edward-malouf** [codeforboston/jobhopper#184]
Identify a fixed color set for all site components.

**Comment by edward-malouf** [comment]
I modified the colors to blend the existing colors with the treemap colors used by Alex R. https://www.figma.com/file/fXQirNUcSUBC5KTJ7hYBO6/JobHopper-interface-2?node-id=0%3A1

**Comment by jedpittman** [comment]
Being Implemented by #205 . Closing
