### ISSUE TITLE
create new transitionsextended endpoint combining transitions and soc-codes data

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#191]
Goal is to have a single endpoint that can be used to query data and returns both the single set of attributes related to the source transition AND all of the transition + related soc attributes for the destination soc code of the transition. 

Deliverable:
1. A filterable endpoint /transitionsextended (same filters as /transitions)
2. Payload should be formatted as follows:
/transitionsextended

results:
{source_soc: { 
source_soc_area_title: 
...
source_soc_file_year:
},
transition_rows: [
  {"id": 36636,
  "soc1": "15-1131",
  "soc2": "11-9031",
  "total_soc": 533764,
  "pi": "0.0000773092",
  "occleaveshare": "0.2133103000" 
"soc2_area_title": "Abilene, TX",
      "soc2_soc_code": "53-7064",
      "soc2_soc_title": "Packers and Packagers, Hand",
      "soc2_hourly_mean_wage": "9.59",
      "soc2_annual_mean_wage": "19950.00",
      "soc2_total_employment": 360,
      "soc2_soc_decimal_code": "53-7064.00",
      "soc2_file_year": 2019  },
{...additional rows/results}
]
}

**Comment by l-cheung** [comment]
Done (https://github.com/codeforboston/jobhopper/pull/201)
