### ISSUE TITLE
Requirements: Data Analyst Scenarios

### ISSUE THREAD

**Issue by rscottlundgren** [codeforboston/jobhopper#20]
Tease out more data analyst scenarios with Ben/Anika.

5. Can we make a lists of data analyst scenarios?

**Comment by carollieb** [comment]
Scenario 1
Find comparisons of risk and opportunity between job transitions.

Scenario 2
There is a large labor pool of hospitality workers who will need to transition to a new career, what are their transition options?

Scenario 3
What are the best rates of transitions for a given MSA?

Scenario 4
What are the skills matches between the large pool of mine company employees who are about to become unemployed and the existing labor market?

Scenario 5
I have new data showing future job growth in my MSA. Who in the existing labor pool are best positioned to transition to these future jobs?

**Comment by jedpittman** [comment]
What does MSA stand for in the scenarios above/what is an example MSA?

**Comment by edward-malouf** [comment]
**Revised Scenarios**

Scenario 1
Find nexus of least amount of effort required for transition, with the highest wage for any given MSA (Metropolitan Statistical Area)

Scenario 2
Using are two or four-digit SOC group, such as mine workers who will need to transition to a new career, what are their transition options? Next step could be Scenario 3.

Scenario 3
What are the skill matches between the large pool of mine company employees who are about to become unemployed and the existing labor market?

Scenario 4
I have new data showing future job growth in my MSA. Who in the existing labor pool are best positioned to transition to these future jobs? This is the same paradigm of the large new employer creating new jobs in the area.

Scenario 5
What occupations are people transitioning to the most within the MSA?

Scenario 6
Compare transitions across different MSAs, for instance, the number of Uber drivers transitioning out of driving jobs, between the greater Boston area and West of Springfield.

Scenario 7
Are the rates of transition faster in one MSA than another? This might point to a more volatile or fertile job market. CK with Gregor if the data set contains time frame.

**Comment by edward-malouf** [comment]
This is a wireframe study of Data Analyst Scenario 1
[Jobhopper board - Data analyst Scenario 1.pdf](https://github.com/codeforboston/jobhopper/files/5003463/Jobhopper.board.-.Data.analyst.Scenario.1.pdf)

**Comment by edward-malouf** [comment]
Is it possible to create the transitions for the following SOCs? This is a scenario for a data analyst if he/she was to view most of the positions eliminated in a coal-fired power plant closure, like the closure of the Paradise Fossil Plant in Kentucky in march of 2020.

17-3023.03. Electrical Engineering Technicians 
51-8013.00. Power Plant Operators 
17-3023.03. Electrical Engineering Technicians
53-7021.00. Crane and Tower Operators
49-3042.00. Mobile Heavy Equipment Mechanics, Except Engines
49-3042.00. Mobile Heavy Equipment Mechanics, Except Engines
43-3031.00. Bookkeeping, Accounting, and Auditing Clerks
13-1071.00. Human Resources Specialists
51-8012.00 - Power Distributors and Dispatchers

**Comment by jedpittman** [comment]
These are requirements and are finished as we're moving from the requirements into build phase.
