### ISSUE TITLE
Update favicon logo, page title, and metadata (1/2)

### ISSUE THREAD

**Issue by alexjball** [codeforboston/jobhopper#210]
This is the first of two issue that help to update the icon that is in the browser and title. 

- Update public/favicon.ico, logo192.png, logo512.png in the public folder of the project and create a new favicon for the project to replace it. 
You can use this favicon generator to create a simple logo: https://favicon.io/favicon-generator/

**Comment by jedpittman** [comment]
The work on the design for the favicon is closed.
