### ISSUE TITLE
Treemap Polish (1/2)

### ISSUE THREAD

**Issue by alexjball** [codeforboston/jobhopper#212]
See code changes from #79 and #110 to incorporate into these changes; some work has been done already.
See tooltip (material tooltip) implementation on the table columns for example. 
- Link to the O*net page for each occupation. See [this example](http://bl.ocks.org/d3noob/8150631#index.html) for how to add hyperlinks to d3 objects. The link can be on either the cell or the job title
- Display transition shares as formatted percents with 2 decimal places. So a transition rate of .12345 would be displayed as “12.35 %”

**Comment by jedpittman** [comment]
closing issue per merged pr.
