### ISSUE TITLE
TransitionPage Polish

### ISSUE THREAD

**Issue by alexjball** [codeforboston/jobhopper#214]
- Make the TransitionTable expand to fill the page horizontally
- Center data loading spinner horizontally
- Center treemap horizontally
- Add bottom margin below results
- Increase space between sections and decrease space between section titles and body (see [mocks](https://www.figma.com/file/fXQirNUcSUBC5KTJ7hYBO6/JobHopper-interface-2?node-id=25%3A25)) Be careful not to change title/body spacing for other pages

**Comment by jedpittman** [comment]
@alexjball this looks good in storybook and tests pass so I am merging in the interest of keeping forward momentum; however, there are two minor items we may want to add to a future ticket but I will leave to you/Ed. (See the tightness of the text in the screenshot below).

See the output at the bottom of the testing

> react-scripts test --watchAll --verbose

  console.log src/services/api/FakeApi.ts:11
    FakeApi.getTransitions { socCode: '12345' }

  console.log src/services/api/FakeApi.ts:19
    FakeApi.getOccupations

PASS src/ducks/__tests__/store.ts
  Store
    √ can be constructed (4ms)
  States
    √ updates the list of states (7ms)
    √ handles update errors (2ms)
  Occupations
    √ updates the list of occupations (1ms)
    √ handles update error (2ms)
  Transitions
    √ updates the list of transitions (3ms)
    √ handles update error (2ms)
    √ handles abortions (1ms)

PASS src/services/api/__tests__/datahelper.ts
  Testing Data Helper Functions
    √ transforms transitions (556ms)

  console.log src/services/api/FakeApi.ts:15
    FakeApi.getStates

  console.log src/services/api/FakeApi.ts:11
    FakeApi.getTransitions { socCode: '12345' }

PASS src/services/api/__tests__/api.ts
  Fake API
    √ Fake can be constructed (4ms)
    √ is provided by default
    √ retrieves occupations (532ms)
    √ retrieves states (519ms)
    √ retrieves transitions (514ms)

PASS src/Main.test.tsx (7.496s)
  √ renders learn react link (203ms)
  √ renders percentage as expected (1ms)

Test Suites: 4 passed, 4 total
Tests:       16 passed, 16 total
Snapshots:   0 total
Time:        9.399s
Ran all test suites.

  console.error node_modules/react-dom/cjs/react-dom.development.js:88
    Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

    * Move data fetching code or side effects to componentDidUpdate.
    * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

    Please update the following components: AutosizeInput, Select

  console.log src/services/api/FakeApi.ts:19
    FakeApi.getOccupations

  console.log src/services/api/FakeApi.ts:15
    FakeApi.getStates


 Merging. Cheers!
![image](https://user-images.githubusercontent.com/18365706/102722581-fde15a80-42cf-11eb-8e70-dfe0017d04b1.png)

**Comment by alexjball** [comment]
Nice catch, @jedpittman . I'll send out a fix for that. Also, just a heads up that you can view CI test results on github so you don't need to run and attach results manually
![Screenshot from 2020-12-20 14-55-21](https://user-images.githubusercontent.com/8595776/102723092-cb396100-42d3-11eb-897f-17fcac509fb5.png)
