### ISSUE TITLE
Update Icons and description information (2/2)

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#216]
Continuing on the work for #210 (don't start until that is done) make these changes in the code
- Remove src/logo.svg (This is the standard react logo today)
- Update description and title in public/index.html and public/manifest.json
- Update public/favicon.ico, logo192.png, logo512.png in public.

**Comment by l-cheung** [comment]
https://github.com/codeforboston/jobhopper/pull/236
