### ISSUE TITLE
Handle Top-Level Jobs with No transitions

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#239]
pick 11-1010 and you'll see that no state can give transitions.
In these cases we should probably either: 
1. Show a message saying no transitions found.
(Edited to remove option -- keeping just the option we want to keep)

**Comment by alexjball** [comment]
Recommend option 2 as we don't know beforehand whether an option has results or not.

**Comment by l-cheung** [comment]
The new `soc_list` endpoint filters down to only include source SOCs with transitions data

**Comment by jedpittman** [comment]
Closing this as duplicated.
