### ISSUE TITLE
Handle Errors

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#240]
In some cases, I found the following console errors in the browser which should be reproducible by choosing F12 and then selecting different top level soc codes from the dropdown using options near the top.

index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

**Comment by alexjball** [comment]
These errors are triggered by the react-select and material-table libraries we use. Unfortunately we can't really fix the error until a fix is implemented in those libraries. The production build of the app does not log these errors and should not be noticeable to end users

**Comment by jedpittman** [comment]
Close as no action required at this point.
