### ISSUE TITLE
Exclude source occupation in transitions-extended response

### ISSUE THREAD

**Issue by alexjball** [codeforboston/jobhopper#245]
The transitions-extended response contains a transition from the source occupation to the source occupation, with incomplete data. We should exclude that element from the response.

http://52.204.195.181:8000/api/v1/jobs/transitions-extended/?soc=11-1021&min_transition_probability=0.02

returns this as one of the transition_rows

```
        {
            "id": 1254,
            "soc1": "11-1021",
            "soc2": "",
            "total_soc": 4905301,
            "pi": 0.04279284,
            "occleaveshare": 0.2221045
        },
```

**Comment by l-cheung** [comment]
Should be fixed as part of https://github.com/codeforboston/jobhopper/pull/257 since there are no longer transitions with a missing destination SOC

```
jobhopperdatabase=# SELECT * FROM jobs_occupationtransitions WHERE soc2 IS NULL;
 id | soc1 | soc2 | total_soc | pi | occleaveshare 
----+------+------+-----------+----+---------------
(0 rows)
```

**Comment by jedpittman** [comment]
Closing this per lillian
