### ISSUE TITLE
Duplicate occupations in soc-list response

### ISSUE THREAD

**Issue by alexjball** [codeforboston/jobhopper#246]
Many occupations occur twice under two different SOC codes. Generally, one of the codes produces results and one does not. We should filter out the invalid occupations. 

Example: 11-1010 and 11-1011 are both Chief Executives but only 11-1011 produces results

**Comment by l-cheung** [comment]
Should be fixed as part of https://github.com/codeforboston/jobhopper/pull/257

**Comment by jedpittman** [comment]
Closing this per Lillian
