### ISSUE TITLE
Treemap revision 1, colors

### ISSUE THREAD

**Issue by edward-malouf** [codeforboston/jobhopper#252]
Attached is a PDF and a link to the frame in Figma of the colors for each of the SOC codes. updated design will be in a separate issue.
[Treemap colorsTreemap colors.pdf](https://github.com/codeforboston/jobhopper/files/5778000/Treemap.colorsTreemap.colors.pdf)

https://www.figma.com/file/RXkmrydtGk66Z3X0AbbKNZ/JoHo-Interface-3?node-id=74%3A61

**Comment by jedpittman** [comment]
marking as complete per Ed via slack
