### ISSUE TITLE
Treemap revision 2, SOC category color application

### ISSUE THREAD

**Issue by edward-malouf** [codeforboston/jobhopper#253]
This mock-up shows the colors applied to an example of the treemap. Also shown are the featured categories below the Treemap. When you hover over each block on the Treemap the box next to the category list highlights as well. The highlight is green to link it with the buttons and distinguish it from the colored blocks.

The typography in the boxes is black, 18 point for the occupation, 20 point for the percentage. It needs to be black for accessibility.

https://www.figma.com/file/RXkmrydtGk66Z3X0AbbKNZ/JoHo-Interface-3?node-id=25%3A37

Attached is a PDF
[MacBook - Tree.. selected cell, hovered cell (2).pdf](https://github.com/codeforboston/jobhopper/files/5783168/MacBook.-.Tree.selected.cell.hovered.cell.2.pdf)

**Comment by edward-malouf** [comment]
Anna suggested the categories be grouped like the version posted on Miro. This will create a less busy design. Working on it now.

**Comment by edward-malouf** [comment]
Updated treemap design with clustered SOC categories
[JoHo treemap, clustered.pdf](https://github.com/codeforboston/jobhopper/files/5784019/JoHo.treemap.clustered.pdf)

Figma
https://www.figma.com/file/RXkmrydtGk66Z3X0AbbKNZ/JoHo-Interface-3?node-id=25%3A37

**Comment by jedpittman** [comment]
marking as complete per Ed via slack
