### ISSUE TITLE
Fix transition share probability conversion in the UI

### ISSUE THREAD

**Issue by l-cheung** [codeforboston/jobhopper#255]
The treemap shows the correct proportions pulled from the API, but the probability in the matrix view is off by a factor of 10. 

E.g. the probability should be 9.5% instead of 0.95% since the proportion is .095

Treemap (correct)
![image](https://user-images.githubusercontent.com/35081231/104094577-b7907300-525f-11eb-9cc9-33b6cbdb4d43.png)

Matrix (incorrect)
![image](https://user-images.githubusercontent.com/35081231/104094581-c119db00-525f-11eb-8a06-e5da89127281.png)

for inputs (in this example)
![image](https://user-images.githubusercontent.com/35081231/104094605-e0b10380-525f-11eb-849a-5a01214827ac.png)

**Comment by jedpittman** [comment]
done. Changes merged
