### ISSUE TITLE
Create a threshold that is easy for us to tweak for min number of transitions

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#264]
Context: Stakeholders are concerned that for some users of the data (certain user types), we might be misleading the users. 

Update the code to have a threshold number of observations (easy to change, perhaps a config var = 5000 for now)
Then only include occupations with total_obs greater than (say) 5,000. This means we are left with 469 occupations rather than 731. 

Fix the api-layer to filter out socs that have fewer than 5000 observations; when adding this to the code, add this as a variable that is easy to fix/change.

**Comment by l-cheung** [comment]
https://github.com/codeforboston/jobhopper/pull/293

**Comment by jedpittman** [comment]
closing this since the code is merged.
