### ISSUE TITLE
Investigate smart search back end

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#265]
Introduce “smart search” function into the search box, so that users can type in a commonly-used name for a job and it will suggest the occupation that they mean.

Stakeholders are looking for a way to let user type in a few letters or term into the box and then it finds the best soc code. See if the onet site has one that we can use (legally) and then let's see what is involved.

**Comment by alexjball** [comment]
ONet has an API for keyword search: https://services.onetcenter.org/reference/mnm/search
Terms of use: https://services.onetcenter.org/terms

**Comment by l-cheung** [comment]
@jedpittman @edward-malouf Curious if either of you have thoughts on these two smart search options: O*Net vs building out our own tool

## O*NET
**Highlights**
* Legal, requires signup w/ technical contact, organization, and app blurb (Annie/Jed): https://services.onetcenter.org/developer/signup
* Limited to 5 requests/second or 50K per day
* Free 
* Requires attribution according to these guidelines: https://services.onetcenter.org/help/license_data#credit 
* Can sometimes return a large list of results, and SOC codes sometimes don't match the ones we have
* Information on O*NET matching method: https://www.onetcenter.org/dl_files/WWS.pdf
* Interactive demo: https://services.onetcenter.org/demo

**Steps to integrate with our database**
(Brainstorming)
* Add a Python script to fetch results from O*NET API based on input occupation name
* Add an API to the Django backend with occupation field that fetches O*NET results and compares them against valid SOC codes in our `jobs_socdescription` table
* Include the ability to filter based on `total_transition_obs` field
* Return SOC codes that appear in both O*NET results and our table
* Needs to be resilient if the O*NET API fails

## Build our own tool
**Highlights**
* Theoretically possible
* Free
* No need to worry about O*NET API being down

**Steps to integrate with our database**
(Brainstorming)
* Run through our list of unique source SOC codes (710 from `jobs_socdescription`) and curate a list of documents with jobs similar to each of them. One way to do that would be a google search for e.g. `jobs like mathematician`
* Create a new table containing these descriptions: SOC code - SOC name - Similar jobs (or document text)
* Add that table to our Django backend by making a new migration (make sure the DB is correctly specified for test vs. production runs)
* Create a new API in the Django backend with a filter that takes a user-input occupation and fuzzy matches against descriptions stored in the table
* Include the ability to filter based on `total_transition_obs` field
* Return the SOC codes that are the closest matches

**Comment by jedpittman** [comment]
Lillian this is a great writeup imo. My hunch is that they will want the onet api. 

Ed would you be able to mock up the line cook example (no matches) and doctor (lots of matches in onet and some that are in our db) as a design? Then we can show/discuss with anna before next steps?

Getting a firm design will help us scope it and decide if we should move forward. 

My hunch right now is that this is between 20-30 hours on the api side and probably 10-15 hours on the front end for most things. I want to get a sense of how close my estimate/guess is and that can come once we have an agreed design. Lillian let me know if you think my guess is fair. 

Thank you both!

**Comment by l-cheung** [comment]
20-30 hrs seems fair for the API side!

**Comment by edward-malouf** [comment]
Will work on it later today

**Comment by l-cheung** [comment]
Useful notes: 
* O*NET API documentation: https://github.com/onetcenter/web-services-samples/blob/master/python-3/OnetWebService.py

**Comment by l-cheung** [comment]
https://github.com/codeforboston/jobhopper/pull/320 <-- Implements smart search backend based on O*NET API. Still testing & will remove draft designation once finished

**Comment by jedpittman** [comment]
Closing this. was part of #320
