### ISSUE TITLE
Ensure that dropdown selection of soc with no observations has the correct message

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#267]
Context: in the demo, we had some socs with no data.

After the user makes a selection, if it is an occupation for which we do not have data, display the text: “We do not have data on occupational transitions for this occupation”

(Note we never expect this to happen, but we want to build it in just in case.)

**Comment by edward-malouf** [comment]
This might not be required with the new dataset and there are no SOCs ending in "0"

**Comment by jkoren** [comment]
I'm working on this.  Is there a demo set of data with an occupation for which we do not have data so I can test? @jedpittman

**Comment by jedpittman** [comment]
@jkoren , I do not expect that we have anything in the live data for you to test.
However, you should be able to build the component and the scenario in storybook using some hard coded fake data that has no transition.

**Comment by jkoren** [comment]
@jedpittman got it.  I am new to storybook, so will have to educate myself.

**Comment by jedpittman** [comment]
instead of npm run start, just do npm run storybook.
Then you'll be able to see/play with some of the other components to see
how it works and then do a story for the component you're interested in.

**Comment by jkoren** [comment]
that makes sense.  so I see the sample data is in src/testing/data/transitionData.ts
for the purpose of this test, I commented out the createTransitions records.
It sounds like the results of changes I make to the code will be reflected in StoryBoard?
