### ISSUE TITLE
Update Wording of Opening Blurb

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#268]
Change the content to this instead:
"JobHopper is a tool to explore new data on mobility between occupations, calculated from around 16 million resumes of U.S. workers, obtained and parsed by Burning Glass Technologies. The tool is designed to help program managers, policy analysts and job coaches explore occupational transitions that job changers have made in recent years. Understanding these transitions can support labor market analysis, program and policy development, and individual job seekers’ aspirations."

**Comment by edward-malouf** [comment]
I reviewed the Opening Blurb with Anna. There was no reference to the academic work. Here is her recommendation, it changes the first sentence into two:

JobHopper is a tool to explore new data on mobility between occupations. This data was calculated by academic researchers from around 16 million resumes of U.S. workers (which were obtained and parsed by Burning Glass Technologies).

**Comment by jkoren** [comment]
@jedpittman I can work on this.
