### ISSUE TITLE
Change wording to use "table" instead of "matrix"

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#270]
call this a “Table” rather than a “Matrix”

Be sure to rerun and fix any automated tests for the UI as needed.

**Comment by jkoren** [comment]
Jed, just FYI - after I did a `git pull `and created a new branch, I couldn't get `npm run start` to work.  
I got this error: ENOENT: no such file or directory, open '/Users/jeffkorenstein/challenges/jobhopper/package.json'`
so I ran `npm install` and then it worked.

**Comment by jedpittman** [comment]
Jeff, yes. You will want to do npm install like you did whenever you’re getting new code to make sure all of the packages are updated.

**Comment by jkoren** [comment]
I updated the button.  
![image](https://user-images.githubusercontent.com/67333843/108789496-635bfc80-7548-11eb-9cb3-11cc7f8edee4.png)
there are many references in the code to this as a matrix.  See below.  Should we change these all to "table" as well?
![image](https://user-images.githubusercontent.com/67333843/108789583-90101400-7548-11eb-83c4-7cd03f48a03f.png)

**Comment by jedpittman** [comment]
I think the ui stuff is the main thing. The code can be left as it is if there would be a lot of changes

**Comment by jkoren** [comment]
that's good.  that might be a lot of work.  

i ran `npm test` and got 4 failed tests, all django tests (below), but I don't think these are because of the change of the button name.  (I tested it with 'Matrix' instead of 'Table' and got the same errors.

Test Suites: 1 failed, 5 passed, 6 total
Tests:       4 failed, 26 passed, 30 total
```

 FAIL  src/services/api/__tests__/DjangoApiClient.ts
  ● DjangoApiClient › Operations › Fetches Occupations (SOC list)

    connect ECONNREFUSED 52.204.195.181:8000



  ● DjangoApiClient › Operations › Fetches State list

    connect ECONNREFUSED 52.204.195.181:8000



  ● DjangoApiClient › Operations › Fetches national transitions

    expect(received).resolves.not.toHaveLength()

    Received promise rejected instead of resolved
    Rejected to value: [Error: connect ECONNREFUSED 52.204.195.181:8000]

      37 | 
      38 |     it('Fetches national transitions', async () => {
    > 39 |       await expect(
         |             ^
      40 |         client.getTransitions({
      41 |           sourceOccupation,
      42 |         })

      at expect (node_modules/react-scripts/node_modules/expect/build/index.js:138:15)
      at Object.<anonymous> (src/services/api/__tests__/DjangoApiClient.ts:39:13)

  ● DjangoApiClient › Operations › Fetches state transitions

    expect(received).resolves.not.toHaveLength()

    Received promise rejected instead of resolved
    Rejected to value: [Error: connect ECONNREFUSED 52.204.195.181:8000]

      45 | 
      46 |     it('Fetches state transitions', async () => {
    > 47 |       await expect(
         |             ^
      48 |         client.getTransitions({
      49 |           sourceOccupation,
      50 |           state: selectedState,

      at expect (node_modules/react-scripts/node_modules/expect/build/index.js:138:15)
      at Object.<anonymous> (src/services/api/__tests__/DjangoApiClient.ts:47:13)

```

**Comment by jedpittman** [comment]
Good stuff. I expect to see those failures. You can submit it now. I will
review/approve.
