### ISSUE TITLE
"Matrix" cleanup

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#271]
- [X] Add a footnote to table: This table /matrix shows the occupations that which {name of occupation} move to when they change occupation. The transition share is the percentage proportion of {name of occupation} who move into a job in each other occupation when they switch occupation. We only show occupations with more than with transition shares greater than 0.2% [of name of occupation] transitioning into them.

Update tooltip text for the matrix visualization:
- [X] Occupation name: Shows occupation that workers in the selected occupation switch into. Clicking on the occupation will take you to the Bureau of Labor Statistics’ O*NET page for that occupation.

- [X] Transition share: This data focuses on workers who move from one occupation to another. The transition share is the percentage of workers from the selected occupation who move into each destination occupation, when they leave their occupation. This is calculated from national data using 16 million workers’ resumes.

- [X] Hourly pay: Average hourly pay in this occupation in {YEAR?}, obtained from the Bureau of Labor Statistics Occupational Employment Statistics database. This shows nationwide pay unless you have selected a specific state.

- [X] Annual salary: Average annual salary in this occupation in {YEAR?}, obtained from the Bureau of Labor Statistics Occupational Employment Statistics database. This shows nationwide salary unless you have selected a specific state.

- [X] SOC Code: I like the text you already have. I would add These codes are 6-digit SOC codes using the 2010 classification system.

- [X] Anika/Gregor: What do you think of this wording? If we can make the “transition share” wording clearer I would be grateful!

- [X] Update headers for the matrix visualization
- [X] Suggest “Occupation name” instead of “Job name”
- [X] Suggest “Average hourly pay” instead of “Hourly pay” and “Average annual salary” instead of “Annual salary”

- [X] Replace the text heading with “Which occupations do {name of occupation} move to?”

**Comment by aniyip** [comment]
A few notes before I put in a PR:

1.) For "Add a footnote to table: " I made the the selected occupation references lowercase. .toLowerCase() can be taken out if we wanted to leave occupation capitalized. 

2.) Along the same lines, with the text heading “Which occupations do {name of occupation} move to?”, should the occupation remain capitalized? Or would we want it lowercase?

3.) For "SOC Code:" I put in what was asked and wonder if we're referencing SOC codes twice: 

>>> "These _codes_ are 6-digit _SOC codes_ using the 2010 classification system."

May I suggest "These 6-digit SOC codes use the 2010 classification system."?

4.) The following still needs to be done:

- For tooltip for hourly pay and annual salary, I left {YEAR?} as is.

**Comment by aniyip** [comment]
The following includes changes from last meeting where we omitted {YEAR}

[TransitionTable.zip](https://github.com/codeforboston/jobhopper/files/6019011/TransitionTable.zip)
C:\Users\Anisan\Desktop\jobhopper\jobhopper\frontend\src\ui\TransitionTable.tsx

[Results.zip](https://github.com/codeforboston/jobhopper/files/6019012/Results.zip)
C:\Users\Anisan\Desktop\jobhopper\jobhopper\frontend\src\ui\Results

To reiterate some notes from earlier:

1.) For "Add a footnote to table: " I made the the selected occupation references lowercase. .toLowerCase() can be taken out if we wanted to leave occupation capitalized.

2.) Along the same lines, with the text heading “Which occupations do {name of occupation} move to?”, should the occupation remain capitalized? Or would we want it lowercase?

3.) For "SOC Code:" I put in what was asked and wonder if we're referencing SOC codes twice:

"These codes are 6-digit SOC codes using the 2010 classification system."

May I suggest "These 6-digit SOC codes use the 2010 classification system."?

**Comment by jedpittman** [comment]
continued on issue #313
