### ISSUE TITLE
Remove the state from the header of the table

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#272]
Goal: Remove the state from the header of the table
This is important because it currently gives the impression that the transition data is at the state level, which is not true. The transition data is at the national level. Only the pay/salary data is at the state level.

Deliverable:
Introduce another header row in the table above “Hourly pay” and “Annual Salary” which says “National” if there is no state selected, and says the name of the state (e.g. “Connecticut”) if the state is selected.

**Comment by ramkelath** [comment]
Was able to get my site serving and look at it carefully enough to see the reported problem.  Next steps:
1. Fork the code and clone it to my site.
2. Fix the issue on my site and submit for code review.

**Comment by ramkelath** [comment]
My React skills are too weak to complete this task.  I believe I was able to locate the changes that would be need - just don't know how to do them.
In jobhopper/frontend/src/ui/TransitionTable.tsx:
1. Around line 29 - the table is defined - we someow need to add another heading line for this task.
2. This new heading line will display the state if there is one, using code like ${selectedState ? `in ${selectedState.name}`

**Comment by jedpittman** [comment]
The stake holders are happy with this as-is so I am closing this issue. There is a lot of information that describes what the data is doing and further questions can be forwarded to us.
