### ISSUE TITLE
Add Treemap Export

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#275]
export the treemap as an image file (e.g. .png or .jpg) which includes the treemap, as well as the JobHopper logo and perhaps a short line of text below it in small font.

The text could say: This visualization shows where {name of occupation} move to when they switch occupation. The visualization was created by Code for Boston’s JobHopper team, using data from 16 million U.S. workers’ resumes compiled by Burning Glass Technologies.

**Comment by edward-malouf** [comment]
Started design of this.

**Comment by jedpittman** [comment]
closing issue per #294
