### ISSUE TITLE
Design Look and Feel for the export of Treemap

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#277]
export the treemap as an image file (e.g. .png or .jpg) which includes the treemap, as well as the JobHopper logo and perhaps a short line of text below it in small font.

The text could say: This visualization shows where {name of occupation} move to when they switch occupation. The visualization was created by Code for Boston’s JobHopper team, using data from 16 million U.S. workers’ resumes compiled by Burning Glass Technologies.

**Comment by edward-malouf** [comment]
This is also attached to #275, see that issue for additional comments.
[Treemap export format.pdf](https://github.com/codeforboston/jobhopper/files/5843599/Treemap.export.format.pdf)

**Comment by jedpittman** [comment]
closed per @edward-malouf
