### ISSUE TITLE
Transitions counter

### ISSUE THREAD

**Issue by edward-malouf** [codeforboston/jobhopper#278]
Consider highlighting the number of transitions found for both the results table and the treemap. 

The idea is to dispel the notion that the percentages add to 100%

The number of transitions is currently shown in the bottom right corner of the table.

Another idea is to identify how many of the target SOC is being sampled. For instance, when you see the 60 transitions for SOC 21-1011 Art Directors, how many individual Art Directors are being sampled?

**Comment by jedpittman** [comment]
Closing this for now. We've updated the look and feel on the treemap a couple of times and we're getting to final state.
