### ISSUE TITLE
LInk to O*net bug

### ISSUE THREAD

**Issue by edward-malouf** [codeforboston/jobhopper#291]
Selecting "11-9199 Managers, All 0ther" produces a "Page not found" error on the My Next Move (O*net) website

This is the URL that results when "11-9199 Managers, All 0ther" is selected:
https://www.mynextmove.org/profile/summary/11-9199.00

This link takes you to the desired page:
 https://www.mynextmove.org/find/search?s=managers%2C+all+other

I tried four occupations, and selected the "11-9199 Managers, All 0ther" from each in both the Table and Treechart, and received the same error message.

Transitions selected
13-2071 Credit Counselors
27-1023 Floral Designers
27-1011 Art Directors
27-1027 SEt and Exhibit Designers

**Comment by jkoren** [comment]
There is some concern by @jedpittman and @alexjball that https://www.mynextmove.org/find/search?s=managers%2C+all+other may not be the best response.  For the short term, just remove the link when the occupation ends with "All Other".

**Comment by jkoren** [comment]
I made the changes.  We may want to consider a link of some sort from the "All Others" category because it looks a little strange when all the other Job Names have links (see screenshot in previous comment).  For now, the error is fixed by removing the 'all others' link.
Tests all pass.

**Comment by jkoren** [comment]
@jedpittman In my instance, we changed the .env file from
`REACT_APP_BASE_API_URL=http://52.204.195.181:8000/api/v1/jobs`
to
`REACT_APP_BASE_API_URL=https://jobhopper.aballslab.com/api/v1/jobs`
I assume I should keep that change in the code I push up?

**Comment by jkoren** [comment]
I got 2 error notifications via email:
Run failed: Django Test - iss-291 (5deabe5)
Run failed: Chromatic Deployment - iss-291 (5deabe5)

**Comment by jedpittman** [comment]
Jeff, we're not changing the .env file in the main code yet. No worries.
I'll handle.
If the tests passed on your side, we're probably fine but I will take a
look.

**Comment by jkoren** [comment]
Ok. Let me know if you want me to change the .env file back and resubmit.
