### ISSUE TITLE
Review And Update Documentation

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#296]
DOD:
All files with .md extension in the repo have been reviewed as follows:
 - Ensure there are no typos
 - Update links to make sure they are working (According to Ed there is a broken link in README.md)
 - Remove any outdated information 
 - Remove information that is now available elsewhere/remove duplicate information

**Comment by jkoren** [comment]
Is it correct to assume this should be done for the whole repo, not just the front end?
Here are the .md files I see:
![image](https://user-images.githubusercontent.com/67333843/107569674-97cdd100-6bb6-11eb-8501-7fb534c238bc.png)

**Comment by jedpittman** [comment]
The whole repo.

**Comment by jkoren** [comment]
I completed this, but having some issues uploading to GIT.  Let's discuss on Tuesday.

**Comment by jkoren** [comment]
Jed, I was looking through my notes on this one, there is still one link broken in References.md.  I was not sure what the correct link was.  
Also, I think there is a missing line in Django.md.

Missing link in References.md
[Linked Here]
(chrome-extension://cbnaodkpfinfiipjblikofhlhlcickei/src/pdfviewer/web/viewer.html?file=https://scholar.harvard.edu/files/stansbury/files/schubertstansburytaskamain_0.pdf)
I tried this too, but it didn't work. (https://scholar.harvard.edu/files/stansbury/files/schubertstansburytaskamain_0.pdf)

DjangoData.md:
Migrations are generally run with the command similar to this (Windows):
I think the command is missing.

**Comment by jkoren** [comment]
Jed, I am not sure If I should re-open this, there is still a broken link in References.md.  I am not sure what the correct link should be.

**Comment by jedpittman** [comment]
closing this as merged previously.
