### ISSUE TITLE
Treemap Redesign Part 1 - Color Code Boxes

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#297]
Split up from #273 
Refer to #252 and #253 with information for layout then....
Create a design/mockup for the treemap that incorporates the following:

* Color code the boxes by their major occupation group.
The file which maps the 6-digit SOC codes to their major occupation group is called soc_hierarchy and is saved as a .csv and as a .dta file in the new data set I sent over on 1/5/2021. The 6-digit SOC code is listed as “detailedoccupation”, the 2-digit SOC major group is listed as “majorgroup” and the name of the occupation group is listed as “majorname”.
* There are 23 total “major” occupation groups.
**The same colors should be assigned to each group in any possible visualization.**

**Comment by sashamaryl** [comment]
this feature is finished and in the code base

**Comment by jedpittman** [comment]
closing per @sashamaryl
