### ISSUE TITLE
Treemap Redesign Part 2 - Add Category Key (this is current next item for sasha)

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#298]
Split from #273 
Refer to #252 and #253 with information for layout then....
Create a design/mockup for the treemap that incorporates the following:

DOD:
* **There should be a key which explains to users easily which group maps to which color (major occupation group names may need to be shortened for ease of viewing in the key!).**

**Comment by jedpittman** [comment]
sent a message to @sashamaryl  on slack about these. Not merging because they are too far out of sync with develop branch.

**Comment by sashamaryl** [comment]
@jedpittman , @Dev1nxavier  The key is actually built, just been having some trouble with the final layout. Ed's designs & discussion last week were really helpful so I think I have what I need to move it forward.
