### ISSUE TITLE
Data Team: Back-End Database Research

### ISSUE THREAD

**Issue by rscottlundgren** [codeforboston/jobhopper#3]
Questions to ask during research:
1. How are we going to store the data - we think we want to use SQL but NoSQL may be better
2. What are the different softwares, frameworks, and data structures that are out there (which are free)? - Pro/Con List Helpful

Tentatively Assigned To: Adam

**Comment by jedpittman** [comment]
@AnnieLa, We determined several weeks ago that we would start with using sqlite and look to potentially move to something like postgres later. What does code for boston typically do for their projects in terms of hosting them? Is there a budget for this and do we have to use any specific provider etc?

**Comment by jedpittman** [comment]
We're closing this issue for now. Jed working with Annie regarding plans for hosting etc but we're settled on Postgres SQL at this point.
