### ISSUE TITLE
Treemap Redesign - Part 4 

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#300]
Split from #273
Refer to #252 and #253 with information for layout then....
Create a design/mockup for the treemap that incorporates the following:

DOD:
* Include an option to color code the boxes instead by average wage
* Ensure that there's a good way to toggle this (consult with Ed as needed)
If possible, boxes in the treemap would stay the same size but users could toggle between a view showing boxes color coded by occupation group, vs color coded by average wage (on a color scale from dark to light).

**Comment by edward-malouf** [comment]
See this link for occupation view and toggle button https://www.figma.com/file/s52Z692iZlxpPV9zc7QMDS/Untitled?node-id=1%3A234

**Comment by Dev1nxavier** [comment]
Issue closed via #316
