### ISSUE TITLE
Treemap Redesign - Part 5 (Sums to 100 - API Changes)

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#301]
Code Enhancements to the transitions-extended api to facilitate better handling for the treemap.

Api Endpoint:
Same existing endpoint as transitions-extended:
returns:

{"source_soc": {
"source_soc_id": 242047,
"source_soc_area_title": "U.S.",
"source_soc_soc_code": "13-2011",
"source_soc_soc_title": "Accountants and Auditors",
"source_soc_hourly_mean_wage": 38.23,
"source_soc_annual_mean_wage": 79520,
"source_soc_total_employment": 1280700,
"source_soc_soc_decimal_code": "13-2011.00",
"source_soc_file_year": 2019
},
"transition_rows": [
{
"id": 1,
"soc1": "13-2011",
"soc2": "11-3031",
"pi": 0.1782961,
"total_transition_obs": 390865.6,
"soc2_id": 241905,
"soc2_area_title": "U.S.",
"soc2_soc_code": "11-3031",
"soc2_soc_title": "Financial Managers",
"soc2_hourly_mean_wage": 70.93,
"soc2_annual_mean_wage": 147530,
"soc2_total_employment": 654790,
"soc2_soc_decimal_code": "11-3031.00",
"soc2_file_year": 2019
},
"category_remainders": [
{"category_id": "12", "category_remainder": defined as the sum of (pi) for all in that category minus the sum of the pi values for those that are returned for that category (soc2).},
{"category_id": "13", "category_remainder": defined as the sum of (pi) for all in that category minus the sum of the pi values for those that are returned for that category (soc2).},
{"category_id": "11", "category_remainder": defined as the sum of (pi) for all in that category minus the sum of the pi values for those that are returned for that category (soc2).},
],
"below_threshold_transitions": [ ]

**Comment by edward-malouf** [comment]
This mock-up shows each occupation with under threshold results, plus other under threshold results that are outside the listed occupations that are over the threshold. 
[21 state 1 (defaults to occupation).pdf](https://github.com/codeforboston/jobhopper/files/6058830/21.state.1.defaults.to.occupation.pdf)

**Comment by edward-malouf** [comment]
The storybook version of the treemap uses the wrong occupation color in several instances.

**Comment by jedpittman** [comment]
Closing this as it looks to be working as expected at this point.
