### ISSUE TITLE
Smart search solution

### ISSUE THREAD

**Issue by edward-malouf** [codeforboston/jobhopper#307]
If a ninth column labeled "commonusage" is added to the <soc_hierarchy_mod.csv> file will this provide results when a user inputs a common name for an occupation that is not currently in the database?

For instance, the noun "doctor" is not in the database, though it is used commonly to refer to a wide variety of health care practitioners.

If it is added to the dataset, using a ninth column, in the same line as, 29-1041 Optometrists, 29-1062 | Family and General Practitioners, and other health occupations commonly referred to as "Doctor" in common usage, then anyone entering "Doctor" during their search will call up these terms as results.

Will this work? A partially completed dataset is attached.
[soc_hierarchy_mod2.xlsx](https://github.com/codeforboston/jobhopper/files/5992207/soc_hierarchy_mod2.xlsx)

**Comment by edward-malouf** [comment]
Updated data file, common names added to 15% of the SOC descriptions
[soc_hierarchy_mod03_02_21.xlsx](https://github.com/codeforboston/jobhopper/files/6072188/soc_hierarchy_mod03_02_21.xlsx)

**Comment by jedpittman** [comment]
Smart search implemented. Stakeholders happy. Closing issue.

**Comment by edward-malouf** [comment]
Yeah!

Content • Design Collaborative LLC
433 Country Way
Scituate, MA 02066
781-378-1484

It takes a village...
http://contentdesign.me/it-takes-a-village-of-institutions-to-make-an-exhibit/









On May 8, 2021, at 9:00 AM, jedpittman ***@***.******@***.***>> wrote:



Smart search implemented. Stakeholders happy. Closing issue.
