### ISSUE TITLE
Chore: Fix missing dependencies

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#310]
Found that we were missing two dependencies when doing initial setup. This is to fix that. 

```
npm WARN storybook-react-router@1.0.8 requires a peer of @storybook/addon-actions@^4.0.0||^5.0.0||5.2.0-beta.13 but none is installed. You must install peer dependencies yourself.
npm WARN ts-jest@26.4.4 requires a peer of jest@>=26 <27 but none is installed. You must install peer dependencies yourself.

```

**Comment by jedpittman** [comment]
I think this is an improvement regarding dependencies. @alexjball , take a look and let me know what you think.

This doesn't seem to have made a difference, presumably because there's not any updates to that package:
```
$ npm install storybook-react-router@latest --save-dev
npm WARN storybook-react-router@1.0.8 requires a peer of @storybook/addon-actions@^4.0.0||^5.0.0||5.2.0-beta.13 but none is installed. You must install peer dependencies yourself.

```

**Comment by alexjball** [comment]
storybook-react-router requires addon-actions v 5 or lower, but we use version 6. Things work with this setup though, so it's likely an issue on the library's side. We can ignore this warning

**Comment by jedpittman** [comment]
jed to double check if this is working and close out if there are no further issues running the storybook code per Alex Ball.
