### ISSUE TITLE
Update UI to incorporate Year information into footnote

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#313]
Update footnote to have information on which years of bls data are used in producing the results. 
"The information related to salary information is sourced from bls <link> and includes YYYY to YYYY with a preference for the most recent data per soc code."

**Comment by LewisStaples** [comment]
Per Lilian's comment in Slack, "BLS file years are pulled from 2017-2019"

**Comment by jedpittman** [comment]
closing issue. Done with PR
