### ISSUE TITLE
Connect "smart search" backend to the frontend

### ISSUE THREAD

**Issue by l-cheung** [codeforboston/jobhopper#327]
The `soc-smart-list` endpoint takes in a user's input keyword and outputs a list of matching SOC codes based on O*NET results merged with transition SOCs. This needs to be connected to the frontend. 

See `DjangoApiClient.ts` as a starting point

**Comment by l-cheung** [comment]
Splitting this into several tickets. 
Backend changes: https://github.com/codeforboston/jobhopper/issues/358

**Comment by alexjball** [comment]
Frontend: #359, #360
