### ISSUE TITLE
Adjust Icon Layout

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#337]
(see PR #347 for changes and fix anything below that is remaining)
See figma for layout: https://www.figma.com/file/2y4zpEh2vRwZCDlbY6kd55/JoHo-final?node-id=0%3A1
We want to ensure that the export chart button doesn't appear if the treemap is not visible.
We want to ensure that the radio toggles are aligned below the visible buttons.
"add wage source to wage button label" 

For Review, please have Alex or Jed review the changes. Reach out them in slack and leave a note in the comments. Once someone reviews, make a comment in the ticket that this looks good and is approved. Another team member will then merge.

A good review will:
Ensure all bullets are done.
Only files/changes to files are related to the changes described.
Ensure the code runs on your machine locally and works as expected.
Ensure that the tests run on your machine locally
There are no unresolved conflicts/errors with tests for the merge request.

**Comment by jkoren** [comment]
per discussion: remove the "Export Chart" button and Occupation Salary choices on the Table View.

**Comment by jkoren** [comment]
An open question if the "Export Chart" button should be removed from the Treechart as in this Figma.
![image](https://user-images.githubusercontent.com/67333843/113077009-40071b80-919e-11eb-8b2e-f67cbd1753f7.png)

**Comment by jkoren** [comment]
Some discussion - Should the "Export Chart" button should be removed from the Treechart as in this Figma.
![image](https://user-images.githubusercontent.com/67333843/113077009-40071b80-919e-11eb-8b2e-f67cbd1753f7.png)
@jedpittman @edward-malouf

**Comment by jkoren** [comment]
Ok.  I will remove the export button.

**Comment by jkoren** [comment]
I made the changes.  The export chart button is removed and Salary/Occupation toggle only appears on TreeMap visualization.  
I kept but commented out the code for "Export Chart" button in case we decide we want the "Export Chart" button later.

**Comment by edward-malouf** [comment]
Look forward to seeing this.

The Treemap should still be exportable, via the download icon on the left.

Thanks!

Ed


Content • Design Collaborative LLC
433 Country Way
Scituate, MA 02066
781-378-1484

What does it take to make history?
http://contentdesign.me/interpreting-roxbury/

On Apr 6, 2021, at 4:05 PM, Jeff Korenstein ***@***.******@***.***>> wrote:



I made the changes. The export chart button is removed and Salary/Occupation toggle only appears on TreeMap visualization.
I kept but commented out the code for "Export Chart" button in case we decide we want the "Export Chart" button later.

**Comment by jkoren** [comment]
Hi Ed,  I made the changes.  I'm not clear on the download button on the left.

![image](https://user-images.githubusercontent.com/67333843/113891040-b3a6bb00-9792-11eb-969a-f7b0ca67d8ed.png)

Jeff

**Comment by edward-malouf** [comment]
My bad, I meant to the the table…


Thanks!!

Ed


Content • Design Collaborative LLC
433 Country Way
Scituate, MA 02066
781-378-1484

It takes a village...
http://contentdesign.me/it-takes-a-village-of-institutions-to-make-an-exhibit/









On Apr 7, 2021, at 11:16 AM, Jeff Korenstein ***@***.******@***.***>> wrote:



Hi Ed, I made the changes. I'm not clear on the download button on the left.

[image]<https://user-images.githubusercontent.com/67333843/113891040-b3a6bb00-9792-11eb-969a-f7b0ca67d8ed.png>

Jeff

**Comment by jedpittman** [comment]
closed by pr #356
