### ISSUE TITLE
Admin: Determine Deployment Options

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#46]
@AnnieLa to follow up with Matt to determine what options we have in terms of hosting. Right now AWS is in the lead because it is what @jedpittman has used, but we need to find out: 
1. What money is available (just for follow up/purposes)
2. What hosting options Code For Boston has already (are there partnerships etc?)

**Comment by AnnieLa** [comment]
I have the word back from Matt.  He says: 

A lot of folks are using Heroku free tier, but on my list is to get us more Digital Ocean credits and/or I can ask Code for America to fund AWS for the project.  Let me know if folks have a preference, but those are the “options” and I can just pursue whatever y’all are most comfortable with.

**Comment by jedpittman** [comment]
Closing this as Annie has given us the answer. We'll need to have a decision as part of our admin work in the next sprint.
