### ISSUE TITLE
Build and Populate Sprint Board

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#48]
- [x] create issues for all items
- [x] create and populate sprint project board in github
- [x] assemble a list of contributors and process

**Comment by jedpittman** [comment]
I'm asking everyone to leave a simple comment here with your Slack name and your github handle so I know the mapping between systems when making assignments.

**Comment by rscottlundgren** [comment]
(For Future Reference When I Return)
Slack: R. Scott Lundgren
GH: rscottlundgren

**Comment by nathan-duddles** [comment]
Slack Name: Nathan Duddles
Github Handle: nathan-duddles

**Comment by l-cheung** [comment]
Slack: Lilian
GitHub: l-cheung

**Comment by azheng1991** [comment]
Slack: Allan Zheng
Github: azheng1991

**Comment by carollieb** [comment]
Looking forward to building an awesome form page!

**Comment by edward-malouf** [comment]
Slack user name: Ed_M
Github: carollieb

**Comment by AnnieLa** [comment]
Slack: Annie LaCourt
Github: Anniela

**Comment by pgibb96** [comment]
Slack: Peter Gibb
Github: pgibb96

**Comment by jedpittman** [comment]
done

**Comment by jedpittman** [comment]
AuburnWings => Adam Finkle.
