### ISSUE TITLE
Develop Initial Onboarding Documentation

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#49]
In order to ensure that it is easy for people to onboard, we should give a one-page document to get started quickly. It's not easy to keep this information up to date and read a long slack channel. 

Create a file called Onboarding.md in MARKDOWN format (similar to the README.md) in the job hopper folder.
https://www.markdownguide.org/basic-syntax/

The document should help someone get onboarded with a 10-15 minute overview; among the information should include:
# One paragraph summary of code for boston
# One paragraph summary of the project
# How to create a login to github
# How to setup git on their machine
# How to create a fork for the repository and download the latest
# How to create a pull request
# One paragraph on expectations: 10hrs/wk, Tuesday's usually optional, but notify via slack, update assigned issue comments 1x/week.

**Comment by jedpittman** [comment]
@AnnieLa @edward-malouf Can you please review these changes and let me know if you'd be comfortable having someone use this as the jump off point for getting onboarded without technical help from us? Then, if they get stuck, one of us can setup time using slack to schedule to unblock them? I'll move this to done if you think it hits the main points. If you have suggested changes, just let me know and I will update the doc.

**Comment by edward-malouf** [comment]
I think the onboarding documentation is clear and precise.

But the summary needs to make clear the origins of the project and how we are merging a private database with public databases. Here is an expanded summary:

Jobhopper is a project designed to provide a web-based interactive tool to leverage privately generated job transition data (hence jobhopper) with data from public sites like O*Net and U.S. Bureau of Labor Statistics to provide information to help policy makers make programming and planning decisions. Two doctoral students and staff from the City of Somerville job development office initiated this project with Code for Boston and provided both the private data and set up interviews with professionals representing the four different personas being used to develop the criteria for the project.

**Comment by jedpittman** [comment]
Closing issue per review with Ed.
