### ISSUE TITLE
Create Initial Material UI (button/link/table etc) Look and Feel (Ed)

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#50]
Goal: Produce at least 3 different look-and-feel basic MVP demos. We will want to incorporate as a start into the look and feel of the first version. Once this is ready, we'll review as a team and take a vote on what to use for what we present in our first demo (obviously we'll take customer input into account) so let's stay flexible.

1. Sign up for code pen.
2. Open this code pen and make a copy of it so you can tweak it:
Add text, button, card as options into a code pen
https://codepen.io/manpreet/pen/mABQVV

3. Look at the JS panel on the far right side and css in the middle. 
4. Update the code to no longer show a login screen, instead show a simple example of each of the following material UI components. Then, update the code pen so that you can change the colors (toggling between 2-3 palettes easily). You can copy/paste the bits from sections of this site: 
https://material-ui.com/components/buttons/

The demo code pen should show the following elements from Material UI so we can see what they look like with different sizes and colors.
Typography
Button
Link
Table
Card

Using a file or tool like this, come up with 3 different color palettes that are generally neutral that could be used. 
https://coolors.co/545e75-63adf2-a7cced-304d6d-82a0bc

**Comment by jedpittman** [comment]
Don't be overwhelmed, but this is the most design-centric task we have in the near term so I wanted to give it to you for a shot. Let's just not get too invested so that if we get other team feedback etc, we can adjust as needed.

**Comment by jedpittman** [comment]
@carolleib I will assign this to you once you accept the invite to contribute on github

**Comment by edward-malouf** [comment]
Please resend the contribute invite to @EdMalo on github

**Comment by edward-malouf** [comment]
Logged into Code Pen, doing the intro

**Comment by edward-malouf** [comment]
I am unable to cut and paste the code from the material-ui site because I do not know how to separate the HTML from the CSS from the JS. However, I can create components in Sketch and export the code from there. Will work on this Sunday.

**Comment by edward-malouf** [comment]
Having difficulty parsing the code but will work on it further tonight

**Comment by edward-malouf** [comment]
First set of design components almost complete, need to create card and link, here is the link to the Figma page:
https://www.figma.com/file/sPliiBwA2zstfFppa2lHaC/JobHopper-Design?node-id=1%3A12

**Comment by jedpittman** [comment]
@edward-malouf, I think we can close this out. If you have additional design work that you want to do, can you please add a ticket and make sure it is in the Grooming Board for next week and we can get it into the next sprint? Thanks for this. It was good to have all of that css/layout information! Reach out if you have any questions.

**Comment by edward-malouf** [comment]
Just saw your note, will create a ticket for additional work.
