### ISSUE TITLE
Create Postman Project Wrapper for automated tests for Python APIs

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#53]
Goal: Build a template and document the process for using postman to test APIs. 

1. Download postman 
https://www.postman.com/
2. Create a simple get request from postman (this can be from any publicly available api if you cannot setup the API for the django project)
3. Setup a simple request which checks the following:
3a. Result exists
3b. Result status code is 200
3c. Result contains some expected value or = some expected value
4. Save and export the test. 
5. Create an APIOnboarding.md markdown file that contains information on how to setup postman, load it and run with the tests.
5. Create a pull request with the exports of these tests and the markdown file  to merge into the DEV branch. Mark the merge request as relating to this issue.

**Comment by zganger** [comment]
I have opened #91 to cover adding the collection for the data APIs and tests for the collection and the time series BLS time series V1 API.

**Comment by l-cheung** [comment]
Note: Also working with aniyip

I'll add a pull request today adding instructions for setting up the API request in postman

**Comment by jedpittman** [comment]
closing issue based on the pull request #91 [ISS-91] looks great
