### ISSUE TITLE
Develop DB Team Documentation

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#56]
Write a v1 DBOnboarding documentation file. 
Create a DBOnboarding.md  markdown file that describes how to:
1. get the postgres database tools installed and running locally
2. Refers to any files needed for the postgres db in our repo and how to get those files and load them locally.
3. Create a pull request to merge this file to dev branch.

**Comment by jedpittman** [comment]
I think this is already covered by the README.md in the data subfolder as part of ISS-69. 
Can someone review that file and confirm that they think that everything basic needed to onboard folks from the Data side is now available? Thanks.

**Comment by jedpittman** [comment]
@l-cheung thanks for reviewing. Comment here and let me know if this is complete and we can close it out. Thanks!

**Comment by l-cheung** [comment]
I think the README has the basics for onboarding data-side. Created a pull request https://github.com/codeforboston/jobhopper/pull/124 that splits out the troubleshooting notes and adds a short description for the BLS data.

**Comment by jedpittman** [comment]
Closing issue based on comment above.
