### ISSUE TITLE
[Volunteer Sprint] Security - Research configuration of django using https

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#62]
How can we ensure that django can be configured to use https? This issue is just to research and distill the things we need in order to setup the django product in an https environment. We will want to ensure that we have the ability to do something similar on our own machines or enable ourselves to run the application under http. 

When the research is done, create follow up issues that deal with getting any of the items setup as needed to run django locally and deploy it with https. 

Document the findings and the tickets created in the security wiki page.

**Comment by l-cheung** [comment]
Issues to research for volunteer-a-thon (Oct 29): 
* Adding `https` to Django layer
* Consider rate limits for pulling data from APIs
* OAuth/other authentication options for the app

Possible resources to get started:
* https://docs.djangoproject.com/en/3.1/topics/security/

**Comment by dlaikhter** [comment]
Here's a summary of our findings.  They are ordered by complexity.
Requirements:
A hostname (can’t generate a certificate without a hostname)
A server (can’t test this without having a webserver running somewhere)

Below are options for acquiring and implementing HTTPS.

Option 1 (best -- especially if already planning to use Cloudflare for DDoS protection):
Use Cloudflare as an HTTPS proxy.  Their endpoint is secured behind HTTPS and then they proxy requests to our server.  As a plus can also be used for DDOS protection.
Related tickets:
https://github.com/codeforboston/jobhopper/issues/170
https://github.com/codeforboston/jobhopper/issues/169

Option 2:
Some domain name providers have an integration with Let’s Encrypt, and will automatically generate/renew certificates with Let’s Encrypt.
Related tickets:
https://github.com/codeforboston/jobhopper/issues/170
https://github.com/codeforboston/jobhopper/issues/169

Option 3:
There is a tool called certbot that will generate, validate, and renew certificates automatically.  It also configures the certificates and the webserver.  It is also agnostic to operating system and webserver software.  It doesn’t work automatically with every provider, so it may end up requiring some amount of nontrivial sysadmin work.
Related tickets:
https://github.com/codeforboston/jobhopper/issues/170
https://github.com/codeforboston/jobhopper/issues/169
https://github.com/codeforboston/jobhopper/issues/171
https://github.com/codeforboston/jobhopper/issues/172
https://github.com/codeforboston/jobhopper/issues/173

Option 4 (worst -- most work required and most prone to errors in setup):
Use a paid certificate through a provider.  It costs around $10/yr, they will activate and renew your certificate automatically.  You will then receive a certificate via email, and will have to install it yourself.  You will also then have to configure nginx/apache.
Related tickets:
https://github.com/codeforboston/jobhopper/issues/170
https://github.com/codeforboston/jobhopper/issues/169
https://github.com/codeforboston/jobhopper/issues/171
https://github.com/codeforboston/jobhopper/issues/172
https://github.com/codeforboston/jobhopper/issues/173

**Comment by jedpittman** [comment]
I think this is done, so I am moving it to the done column but won't close until I circle back with Lilian.

**Comment by jedpittman** [comment]
We're closing this; Alex ball did this as part of the deployment process.
