### ISSUE TITLE
Design a Job Hopper Logo

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#63]
JobHopper should have a logo that we can use in the application and in any kind of advertising we do. The logo for now can be straightforward, but otherwise, let;s create something that is both professional and gives the project a little bit of personality.
BONUS: also include a favicon that would be similar in style/color but could be used for bookmark purposes.

**Comment by edward-malouf** [comment]
This is right up my alley, I will get to work on it.

**Comment by jedpittman** [comment]
@edward-malouf , I see the logo in the figma. Can you upload it to slack or attach it to this item in an image format so that we can use it or add it as a pull request?

**Comment by edward-malouf** [comment]
Will do, I have other ideas in pencil form that I was going to work on and share, but am happy to make this one available now.


Content • Design Collaborative LLC 
433 Country Way
Scituate, MA 02066
781-378-1484  

Bonding over wallpaper
http://contentdesign.me/historical-finishes/

**Comment by jedpittman** [comment]
closing issue since logo was merged.
