### ISSUE TITLE
Data: Load BLS SOC codes into PostgreSQL with O*Net URLs and overwrite any URLs that do not resolve

### ISSUE THREAD

**Issue by l-cheung** [codeforboston/jobhopper#64]
See issues #52 (base case for loading SOC O*Net URL) and #18 (BLS data loading). 

Load the Postgres BLS data with the SOC code and any 'overrides' to the url that need to be handled. We can ping the automatically generated URLs to make sure they resolve to a valid page, overriding any that do not resolve.

**Comment by l-cheung** [comment]
Can tackle this after issue #65

**Comment by jedpittman** [comment]
@l-cheung please let me know if I am wrong and feel free to reopen this...but I think we have something working for all soc codes even unmatched ones so I am closing this issue.
