### ISSUE TITLE
Data: Migrate BLS table(s) to Postgres instead of Sqlite

### ISSUE THREAD

**Issue by l-cheung** [codeforboston/jobhopper#65]
BLS scraping process should load cleaned wage/employment data into a Postgres database instead of Sqlite.

**Comment by l-cheung** [comment]
https://github.com/codeforboston/jobhopper/pull/69

**Comment by jedpittman** [comment]
Lillian, you did the major work here as part of #69. I've updated the README to remove some old stuff and also removed some of the stuff in the directory related to sql-lite. Other files might be usable when we add those tables into postgres so I am leaving them for now.

**Comment by jedpittman** [comment]
pull request review requested.

**Comment by jedpittman** [comment]
closing issue. Merge complete
