### ISSUE TITLE
Documentation: Installation and deployment of PostgreSQL server.

### ISSUE THREAD

**Issue by EndyPremier** [codeforboston/jobhopper#66]
README.md should include how to setup a PostgreSQL server -- installing Postgres and setting up (and configuring) role and database. This could include setting up environment variables.

**Comment by EndyPremier** [comment]
Note that for the time being this is all being for Linux environment. Hopefully, this would extend for Windows and Mac but Linux should be the minimum.

**Comment by jedpittman** [comment]
done
