### ISSUE TITLE
Add code coverage to the python code

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#82]
Investigate Integration with coverage.py for Django API code and DB python loading code.
https://docs.djangoproject.com/en/3.1/topics/testing/advanced/#topics-testing-code-coverage

**Comment by zganger** [comment]
Opened #150 (#149 had git trouble).

**Comment by zganger** [comment]
I'm not sure I have permissions to move this task to review state- else I simply don't know how.

**Comment by jedpittman** [comment]
@zganger , that is an issue with our permissions. I'm moving it for you.
