### ISSUE TITLE
[Volunteer Sprint] Security/Data - Add CICD actions for DJANGO and/or backend data processes

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#83]
Do this work on your fork.
Add a github action that grabs the code and executes the automated tests for django. 
python manage.py runtest (I think this is the correct syntax)

**Comment by l-cheung** [comment]
Volunteer-a-thon Goal: Adding point in time and rerunability to the load process. {This would allow us to be confident that the process would work as the data changes in our sources and would just expire data and not remove it/truncate it}

Possible breakdown of issues:
* Integrate GitHub Actions to execute automated tests for Django
* Consider adding timestamps to allow for data updates/de-duplication
* Explore other ways to improve the data pipeline

**Comment by jedpittman** [comment]
Let's be sure this is done. Then also, see if we could somehow incorporate the output as coverage into the results so that it was easier to see if the project's tests are truly working as expected.
